### ISSUE TITLE
Method Illuminate\Support\Collection::findFieldByAttribute does not exist.

### ISSUE THREAD

**Issue by academici** [dcasia/nova-json-wrapper#1]
Laravel 6.4
Nova 2.6

Getting an error, when register trait HasJsonWrapper in Nova resource

**Comment by milewski** [comment]
Hi can you post how you are using it, a full example so I can try to find the error

**Comment by academici** [comment]
Sorry, i forgot add json field to fillable

**Comment by academici** [comment]
@milewski, there is a problem.
Create a laravel 6.4, nova 2.6
Add to model user
```php
class User extends Model
{
    protected $casts = [
        'options' => 'array'
    ];
}
```
Create resource with trait
```php
use HasJsonWrapper;
```
Get an error with 
```php
JsonWrapper::make('options', [
        
            Text::make('First Name')->rules('required'),
            Text::make('Last Name')->rules('required'),
])
```
and without JsonWrapper::make

**Comment by milewski** [comment]
What error did you get ？

**Comment by academici** [comment]
Error getting when use BelongsTo field.
```php
BelongsTo::make("Car", Car::class)->nullable(),
```
If comment BelongsTo, no errors, but json field not showing
```php
JsonWrapper::make("rating", [
  Text::make('Total')->rules('required')
]
```

**Comment by milewski** [comment]
@academici your BelongsTo looks incorrect, it should had been

```php
BelongsTo::make("Car", 'car',Car::class)->nullable(),
```

**Comment by academici** [comment]
@milewski, 'car' added, but error showing

**Comment by milewski** [comment]
@academici please try version [v0.1.3](https://github.com/dcasia/nova-json-wrapper/releases/tag/v0.1.3) see if it works correctly for you now
