### ISSUE TITLE
Issue using it  with flexible content

### ISSUE THREAD

**Issue by scramatte** [dcasia/nova-json-wrapper#17]
Hello,

When I use it with flexible content I've got following error

`Call to undefined method App\Nova\Flexible\Layouts\EmailLayout::replicate()`

Any idea of what occurs?

**Comment by milewski** [comment]
Well when storing the fields in the database this package will attempt to clone the underlying model... however when you use the flexible content the underlying model isn't an actual model but something similar which is lacking the replicate() method in it...

**Comment by scramatte** [comment]
As a workaround I’ve added replicate method in the layout class that return an  instance of an empty eloquent model.

**Comment by milewski** [comment]
I think you can return a Fluent object perhaps filled with the data from your layout... not sure if your workaround actually worked

**Comment by scramatte** [comment]
Effectively , it doesn't works, I need to search a way to fill with data...

**Comment by scramatte** [comment]
As you told me you need to use Fluent object. May it would be interesting to create a Trait  for this?

```
    public function replicate()    {
        return  new Fluent($this->getAttributes());
    }
```
