### ISSUE TITLE
Nested fields don't work

### ISSUE THREAD

**Issue by onemoreahmad** [dcasia/nova-json-wrapper#3]
Awesome package, exactly what I was looking for, thanks for the great work!

However, it works perfect without nested fields, using your example :
```
  JsonWrapper::make('options', [
            Text::make('First Name')->rules('required'),
            Text::make('Last Name')->rules('required'),
        
            JsonWrapper::make('body_mass', [  
                Text::make('Weight')->rules('required'),
                Text::make('Height')->rules('required'),          
            ])
        ])
```

Then adding & updating the data for three times, nothing get updated but instead it adds more data to the database, here is what I got in the database:

<img width="324" alt="Screen Shot 2019-11-22 at 8 42 52 PM" src="https://user-images.githubusercontent.com/1885785/69448000-b7d26400-0d68-11ea-9556-6d117d6b3b70.png">

**Comment by milewski** [comment]
Fixed [v0.1.4](https://github.com/dcasia/nova-json-wrapper/releases/tag/v0.1.4)
