### ISSUE TITLE
Method name collisions

### ISSUE THREAD

**Issue by barnabaskecskes** [dcasia/nova-json-wrapper#4]
If I use the traits from this package and the `dcasia/conditional-container` package as the documentations suggest, the latter trait's methods will be ignored therefore these packages won't play ball with each other. What is your suggestion?

**Comment by milewski** [comment]
Hi @barnabaskecskes , unfortunately, Nova doesn't provide any way for a package to hook into its "life cycle" so in order to archive some functionality we need to "override" some methods that nova will call on its request lifecycle.. but you still can use both packages together by creating subclasses and extending them..  for example:

```php
class WithJsonWrapperField extends Resource {

     use HasJsonWrapper;

}
```

```php
class WithConditionalContainerField extends WithJsonWrapperField {
    
     use HasConditionalContainer;

}
```

```php
class YourResourceClass extends WithConditionalContainerField
{
    public function field()
    {
        return [
            ConditionalContainer::make([
                JsonWrapper::make(...)
            ])
        ];
    }
}
```

**Comment by barnabaskecskes** [comment]
Thanks for the response. I think this is exactly the same as just dropping the `HasJsonWrapper` trait and using it like below (which I have ended up doing in my case), but please correct me if I'm wrong?
```php
class MyResourceClass
{
	use HasConditionalContainer;

	public function field()
    {
        return [
            ConditionalContainer::make([
                JsonWrapper::make(...)
            ])
        ];
    }
}
```

**Comment by milewski** [comment]
Without the HasJsonWrapper, your resource won't display correctly on details view

What that trait does is, when you are on the detail views it merge all its given fields into a your main fields array, so it display as if there wasn't any json wrapper at all, if you remove it nova will try to render it, but there isn't any detail field definition for json wrapper, so all your nested fields I'll be gone on details view...

**Comment by bolechen** [comment]
i try to work the whole afternoon, but not works fine together :(
could you give more help?

very thx. this is my test code.

[Nova.zip](https://github.com/dcasia/nova-json-wrapper/files/4002261/Nova.zip)

**Comment by milewski** [comment]
Maybe something has changed in the latest version of nova, the project I use both packages together uses nova `2.5` so I will need some time to figure out what's wrong, your example looks correct

**Comment by bolechen** [comment]
any news for this? @milewski  thx

**Comment by u12206050** [comment]
Also would like a fix for this, using nova version 3.
